### ISSUE TITLE
Poke a mango, not lift a mango!

### ISSUE THREAD

**Issue by cramertj** [nabijaczleweli/poke-a-mango#4]
Game detects when I lift my finger off a mango, not when I poke it! False advertising. 0/10.

Clicks should probably registered on mouse-down, not mouse-up 😆

**Comment by nabijaczleweli** [comment]
Whoops, I'm pretty sure it's a limitation of `conrod`.

**Comment by nabijaczleweli** [comment]
Confirmed, [button can't react to mouse down](http://docs.piston.rs/conrod/conrod/widget/button/struct.TimesClicked.html), only to full click.
Sorry, mate.
